# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Trap Square' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trap Square

end

target 'Trap Square MessagesExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trap Square MessagesExtension
  pod 'DuckUI'
  pod 'SwiftyStoreKit'
  pod 'KeychainSwift'
  pod 'Gifu'

end
